import {Link} from "react-router-dom";
import { FormattedMessage } from "react-intl";

const OurTeamData =[
    {
        emri:<FormattedMessage id="arianit" defaultMessage="Aritanit Tershnjaku"/>,
        role:<FormattedMessage id="role" defaultMessage="Instruktor Shkolla Digjitale Prizren"/>,
        skills:<FormattedMessage id="skills" defaultMessage="Skills"/>,
        tags8:<FormattedMessage id="tags8" defaultMessage="Manager"/>,
        tags:<FormattedMessage id="tags" defaultMessage="HTML"/>,
        tags1:<FormattedMessage id="tags1" defaultMessage="CSS"/>,
        tags2:<FormattedMessage id="tags2" defaultMessage="JavaScript"/>,
        tags3:<FormattedMessage id="tags3" defaultMessage="PHP"/>,
        tags4:<FormattedMessage id="tags4" defaultMessage="MySql"/>,
        tags04:<FormattedMessage id="tags04" defaultMessage="MySql"/>,
        tags5:<FormattedMessage id="tags5" defaultMessage="Jquery"/>,
        tags6:<FormattedMessage id="tags6" defaultMessage="Laravel"/>,
        tags7:<FormattedMessage id="tags7" defaultMessage="React"/>,
        tags10:<FormattedMessage id="tags10" defaultMessage="Java"/>,
        tags9:<FormattedMessage id="tags9" defaultMessage="WebDeveloper"/>,
        closeBTN:<Link ><FormattedMessage id="Close" defaultMessage="Close"/></Link>,
        closeBTN1:<Link ><FormattedMessage id="X" defaultMessage="X"/></Link>
    },
    {
        emri:<FormattedMessage id="arianit" defaultMessage="Fatjona Hooxhaj"/>,
        role:<FormattedMessage id="role" defaultMessage="Instruktor Shkolla Digjitale Prizren"/>,
        skills:<FormattedMessage id="skills" defaultMessage="Skills"/>,
        tags8:<FormattedMessage id="tags8" defaultMessage="Manager"/>,
        tags:<FormattedMessage id="tags" defaultMessage="HTML"/>,
        tags1:<FormattedMessage id="tags1" defaultMessage="CSS"/>,
        tags2:<FormattedMessage id="tags2" defaultMessage="JavaScript"/>,
        tags3:<FormattedMessage id="tags3" defaultMessage="PHP"/>,
        tags4:<FormattedMessage id="tags4" defaultMessage="MySql"/>,
        tags04:<FormattedMessage id="tags04" defaultMessage="MySql"/>,
        tags5:<FormattedMessage id="tags5" defaultMessage="Jquery"/>,
        tags6:<FormattedMessage id="tags6" defaultMessage="Laravel"/>,
        tags7:<FormattedMessage id="tags7" defaultMessage="React"/>,
        tags10:<FormattedMessage id="tags10" defaultMessage="Java"/>,
        tags9:<FormattedMessage id="tags9" defaultMessage="WebDeveloper"/>,
        closeBTN:<Link ><FormattedMessage id="Close" defaultMessage="Close"/></Link>,
        closeBTN1:<Link ><FormattedMessage id="X" defaultMessage="X"/></Link>
    },

    {
        emri:<FormattedMessage id="arianit" defaultMessage="Kebir Cesko"/>,
        role:<FormattedMessage id="role" defaultMessage="Instruktor Shkolla Digjitale Prizren"/>,
        skills:<FormattedMessage id="skills" defaultMessage="Skills"/>,
        tags8:<FormattedMessage id="tags8" defaultMessage="Manager"/>,
        tags:<FormattedMessage id="tags" defaultMessage="HTML"/>,
        tags1:<FormattedMessage id="tags1" defaultMessage="CSS"/>,
        tags2:<FormattedMessage id="tags2" defaultMessage="JavaScript"/>,
        tags3:<FormattedMessage id="tags3" defaultMessage="PHP"/>,
        tags4:<FormattedMessage id="tags4" defaultMessage="MySql"/>,
        tags04:<FormattedMessage id="tags04" defaultMessage="MySql"/>,
        tags5:<FormattedMessage id="tags5" defaultMessage="Jquery"/>,
        tags6:<FormattedMessage id="tags6" defaultMessage="Laravel"/>,
        tags7:<FormattedMessage id="tags7" defaultMessage="React"/>,
        tags10:<FormattedMessage id="tags10" defaultMessage="Java"/>,
        tags9:<FormattedMessage id="tags9" defaultMessage="WebDeveloper"/>,
        closeBTN:<Link ><FormattedMessage id="Close" defaultMessage="Close"/></Link>,
        closeBTN1:<Link ><FormattedMessage id="X" defaultMessage="X"/></Link>
    },

    {
        emri:<FormattedMessage id="arianit" defaultMessage="Floranda Qenaj"/>,
        role:<FormattedMessage id="role" defaultMessage="Instruktor Shkolla Digjitale Prizren"/>,
        skills:<FormattedMessage id="skills" defaultMessage="Skills"/>,
        tags8:<FormattedMessage id="tags8" defaultMessage="Manager"/>,
        tags:<FormattedMessage id="tags" defaultMessage="HTML"/>,
        tags1:<FormattedMessage id="tags1" defaultMessage="CSS"/>,
        tags2:<FormattedMessage id="tags2" defaultMessage="JavaScript"/>,
        tags3:<FormattedMessage id="tags3" defaultMessage="PHP"/>,
        tags4:<FormattedMessage id="tags4" defaultMessage="MySql"/>,
        tags04:<FormattedMessage id="tags04" defaultMessage="MySql"/>,
        tags5:<FormattedMessage id="tags5" defaultMessage="Jquery"/>,
        tags6:<FormattedMessage id="tags6" defaultMessage="Laravel"/>,
        tags7:<FormattedMessage id="tags7" defaultMessage="React"/>,
        tags10:<FormattedMessage id="tags10" defaultMessage="Java"/>,
        tags9:<FormattedMessage id="tags9" defaultMessage="WebDeveloper"/>,
        closeBTN:<Link ><FormattedMessage id="Close" defaultMessage="Close"/></Link>,
        closeBTN1:<Link ><FormattedMessage id="X" defaultMessage="X"/></Link>
    },

    {
        emri:<FormattedMessage id="arianit" defaultMessage="Anesa Salihu"/>,
        role:<FormattedMessage id="role" defaultMessage="Instruktor Shkolla Digjitale Prizren"/>,
        skills:<FormattedMessage id="skills" defaultMessage="Skills"/>,
        tags8:<FormattedMessage id="tags8" defaultMessage="Manager"/>,
        tags:<FormattedMessage id="tags" defaultMessage="HTML"/>,
        tags1:<FormattedMessage id="tags1" defaultMessage="CSS"/>,
        tags2:<FormattedMessage id="tags2" defaultMessage="JavaScript"/>,
        tags3:<FormattedMessage id="tags3" defaultMessage="PHP"/>,
        tags4:<FormattedMessage id="tags4" defaultMessage="MySql"/>,
        tags04:<FormattedMessage id="tags04" defaultMessage="MySql"/>,
        tags5:<FormattedMessage id="tags5" defaultMessage="Jquery"/>,
        tags6:<FormattedMessage id="tags6" defaultMessage="Laravel"/>,
        tags7:<FormattedMessage id="tags7" defaultMessage="React"/>,
        tags10:<FormattedMessage id="tags10" defaultMessage="Java"/>,
        tags9:<FormattedMessage id="tags9" defaultMessage="WebDeveloper"/>,
        closeBTN:<Link ><FormattedMessage id="Close" defaultMessage="Close"/></Link>,
        closeBTN1:<Link ><FormattedMessage id="X" defaultMessage="X"/></Link>
    },

    {
        emri:<FormattedMessage id="arianit" defaultMessage="Hatixhe Piraj"/>,
        role:<FormattedMessage id="role" defaultMessage="Instruktor Shkolla Digjitale Prizren"/>,
        skills:<FormattedMessage id="skills" defaultMessage="Skills"/>,
        tags8:<FormattedMessage id="tags8" defaultMessage="Manager"/>,
        tags:<FormattedMessage id="tags" defaultMessage="HTML"/>,
        tags1:<FormattedMessage id="tags1" defaultMessage="CSS"/>,
        tags2:<FormattedMessage id="tags2" defaultMessage="JavaScript"/>,
        tags3:<FormattedMessage id="tags3" defaultMessage="PHP"/>,
        tags4:<FormattedMessage id="tags4" defaultMessage="MySql"/>,
        tags04:<FormattedMessage id="tags04" defaultMessage="MySql"/>,
        tags5:<FormattedMessage id="tags5" defaultMessage="Jquery"/>,
        tags6:<FormattedMessage id="tags6" defaultMessage="Laravel"/>,
        tags7:<FormattedMessage id="tags7" defaultMessage="React"/>,
        tags10:<FormattedMessage id="tags10" defaultMessage="Java"/>,
        tags9:<FormattedMessage id="tags9" defaultMessage="WebDeveloper"/>,
        closeBTN:<Link ><FormattedMessage id="Close" defaultMessage="Close"/></Link>,
        closeBTN1:<Link ><FormattedMessage id="X" defaultMessage="X"/></Link>
    },
    {
        emri:<FormattedMessage id="arianit" defaultMessage="Almir Pinduk"/>,
        role:<FormattedMessage id="role" defaultMessage="Instruktor Shkolla Digjitale Prizren"/>,
        skills:<FormattedMessage id="skills" defaultMessage="Skills"/>,
        tags8:<FormattedMessage id="tags8" defaultMessage="Manager"/>,
        tags:<FormattedMessage id="tags" defaultMessage="HTML"/>,
        tags1:<FormattedMessage id="tags1" defaultMessage="CSS"/>,
        tags2:<FormattedMessage id="tags2" defaultMessage="JavaScript"/>,
        tags3:<FormattedMessage id="tags3" defaultMessage="PHP"/>,
        tags4:<FormattedMessage id="tags4" defaultMessage="MySql"/>,
        tags04:<FormattedMessage id="tags04" defaultMessage="MySql"/>,
        tags5:<FormattedMessage id="tags5" defaultMessage="Jquery"/>,
        tags6:<FormattedMessage id="tags6" defaultMessage="Laravel"/>,
        tags7:<FormattedMessage id="tags7" defaultMessage="React"/>,
        tags10:<FormattedMessage id="tags10" defaultMessage="Java"/>,
        tags9:<FormattedMessage id="tags9" defaultMessage="WebDeveloper"/>,
        closeBTN:<Link ><FormattedMessage id="Close" defaultMessage="Close"/></Link>,
        closeBTN1:<Link ><FormattedMessage id="X" defaultMessage="X"/></Link>
    },
    {
        emri:<FormattedMessage id="arianit" defaultMessage="Vesa Susuri"/>,
        role:<FormattedMessage id="role" defaultMessage="Instruktor Shkolla Digjitale Prizren"/>,
        skills:<FormattedMessage id="skills" defaultMessage="Skills"/>,
        tags8:<FormattedMessage id="tags8" defaultMessage="Manager"/>,
        tags:<FormattedMessage id="tags" defaultMessage="HTML"/>,
        tags1:<FormattedMessage id="tags1" defaultMessage="CSS"/>,
        tags2:<FormattedMessage id="tags2" defaultMessage="JavaScript"/>,
        tags3:<FormattedMessage id="tags3" defaultMessage="PHP"/>,
        tags4:<FormattedMessage id="tags4" defaultMessage="MySql"/>,
        tags04:<FormattedMessage id="tags04" defaultMessage="MySql"/>,
        tags5:<FormattedMessage id="tags5" defaultMessage="Jquery"/>,
        tags6:<FormattedMessage id="tags6" defaultMessage="Laravel"/>,
        tags7:<FormattedMessage id="tags7" defaultMessage="React"/>,
        tags10:<FormattedMessage id="tags10" defaultMessage="Java"/>,
        tags9:<FormattedMessage id="tags9" defaultMessage="WebDeveloper"/>,
        closeBTN:<Link ><FormattedMessage id="Close" defaultMessage="Close"/></Link>,
        closeBTN1:<Link ><FormattedMessage id="X" defaultMessage="X"/></Link>
    },
    {
        emri:<FormattedMessage id="arianit" defaultMessage="Malart Peqani"/>,
        role:<FormattedMessage id="role" defaultMessage="Instruktor Shkolla Digjitale Prizren"/>,
        skills:<FormattedMessage id="skills" defaultMessage="Skills"/>,
        tags8:<FormattedMessage id="tags8" defaultMessage="Manager"/>,
        tags:<FormattedMessage id="tags" defaultMessage="HTML"/>,
        tags1:<FormattedMessage id="tags1" defaultMessage="CSS"/>,
        tags2:<FormattedMessage id="tags2" defaultMessage="JavaScript"/>,
        tags3:<FormattedMessage id="tags3" defaultMessage="PHP"/>,
        tags4:<FormattedMessage id="tags4" defaultMessage="MySql"/>,
        tags04:<FormattedMessage id="tags04" defaultMessage="MySql"/>,
        tags5:<FormattedMessage id="tags5" defaultMessage="Jquery"/>,
        tags6:<FormattedMessage id="tags6" defaultMessage="Laravel"/>,
        tags7:<FormattedMessage id="tags7" defaultMessage="React"/>,
        tags10:<FormattedMessage id="tags10" defaultMessage="Java"/>,
        tags9:<FormattedMessage id="tags9" defaultMessage="WebDeveloper"/>,
        closeBTN:<Link ><FormattedMessage id="Close" defaultMessage="Close"/></Link>,
        closeBTN1:<Link ><FormattedMessage id="X" defaultMessage="X"/></Link>
    },
    {
        emri:<FormattedMessage id="arianit" defaultMessage="Lendrit Kolgeci"/>,
        role:<FormattedMessage id="role" defaultMessage="Instruktor Shkolla Digjitale Prizren"/>,
        skills:<FormattedMessage id="skills" defaultMessage="Skills"/>,
        tags8:<FormattedMessage id="tags8" defaultMessage="Manager"/>,
        tags:<FormattedMessage id="tags" defaultMessage="HTML"/>,
        tags1:<FormattedMessage id="tags1" defaultMessage="CSS"/>,
        tags2:<FormattedMessage id="tags2" defaultMessage="JavaScript"/>,
        tags3:<FormattedMessage id="tags3" defaultMessage="PHP"/>,
        tags4:<FormattedMessage id="tags4" defaultMessage="MySql"/>,
        tags04:<FormattedMessage id="tags04" defaultMessage="MySql"/>,
        tags5:<FormattedMessage id="tags5" defaultMessage="Jquery"/>,
        tags6:<FormattedMessage id="tags6" defaultMessage="Laravel"/>,
        tags7:<FormattedMessage id="tags7" defaultMessage="React"/>,
        tags10:<FormattedMessage id="tags10" defaultMessage="Java"/>,
        tags9:<FormattedMessage id="tags9" defaultMessage="WebDeveloper"/>,
        closeBTN:<Link ><FormattedMessage id="Close" defaultMessage="Close"/></Link>,
        closeBTN1:<Link ><FormattedMessage id="X" defaultMessage="X"/></Link>
    },
]

export default OurTeamData;
